project_id = "yoebdmrpmftlwbwyzzjq"

[functions.ebay-search]
verify_jwt = false

[functions.gem-rate]
verify_jwt = false

[functions.fetch-psa-pop]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false